image: gitpod/workspace-mysql:branch-mysql

tasks:
    - init: composer --no-dev --ignore-platform-reqs install && npm i
      command: php -S 127.0.0.1:8080

ports:
    - port: 3306
    - port: 8080
      onOpen: open-preview
